/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginregister;

import java.awt.Color;
import java.io.File;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Samantha
 */
public class RegisterClass extends javax.swing.JFrame {

    /**
     * Creates new form RegisterClass
     */
    
    //Create a variable to set the image path
    String image_path = null;
    
    public RegisterClass() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        //Create a button group for the Radiobuttons. Only allows user to click 1 of them. Cannot be both
        ButtonGroup bgroup = new ButtonGroup();
        bgroup.add(malebutton);
        bgroup.add(femalebutton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Close_label = new javax.swing.JLabel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        close_panel2 = new javax.swing.JPanel();
        Close_label2 = new javax.swing.JLabel();
        minimize_panel2 = new javax.swing.JPanel();
        minimize_label2 = new javax.swing.JLabel();
        ictxt = new javax.swing.JTextField();
        addresstxt = new javax.swing.JTextField();
        Nametxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        phonetxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        gendertxt = new javax.swing.JLabel();
        malebutton = new javax.swing.JRadioButton();
        femalebutton = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        imagebutton = new javax.swing.JButton();
        labelimage = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        buttonLogin = new javax.swing.JButton();
        pwdtxt = new javax.swing.JPasswordField();
        cfmpwdtxt = new javax.swing.JPasswordField();
        existedacc = new javax.swing.JLabel();

        Close_label.setBackground(new java.awt.Color(255, 255, 255));
        Close_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Close_label.setForeground(new java.awt.Color(232, 92, 0));
        Close_label.setText("x");
        Close_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Close_labelMouseClicked(evt);
            }
        });

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jPanel2.setBackground(new java.awt.Color(232, 92, 0));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sign Up");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginregister/icons8-sign-up-40.png"))); // NOI18N

        close_panel2.setBackground(new java.awt.Color(0, 0, 51));
        close_panel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                close_panel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                close_panel2MouseExited(evt);
            }
        });

        Close_label2.setBackground(new java.awt.Color(0, 0, 51));
        Close_label2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Close_label2.setForeground(new java.awt.Color(232, 92, 0));
        Close_label2.setText(" x ");
        Close_label2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Close_label2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Close_label2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Close_label2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Close_label2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout close_panel2Layout = new javax.swing.GroupLayout(close_panel2);
        close_panel2.setLayout(close_panel2Layout);
        close_panel2Layout.setHorizontalGroup(
            close_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Close_label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        close_panel2Layout.setVerticalGroup(
            close_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(close_panel2Layout.createSequentialGroup()
                .addComponent(Close_label2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        minimize_panel2.setBackground(new java.awt.Color(0, 0, 52));
        minimize_panel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimize_panel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimize_panel2MouseExited(evt);
            }
        });

        minimize_label2.setBackground(new java.awt.Color(0, 0, 51));
        minimize_label2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        minimize_label2.setForeground(new java.awt.Color(232, 92, 0));
        minimize_label2.setText(" - ");
        minimize_label2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        minimize_label2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_label2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimize_label2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimize_label2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout minimize_panel2Layout = new javax.swing.GroupLayout(minimize_panel2);
        minimize_panel2.setLayout(minimize_panel2Layout);
        minimize_panel2Layout.setHorizontalGroup(
            minimize_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(minimize_label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );
        minimize_panel2Layout.setVerticalGroup(
            minimize_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, minimize_panel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(minimize_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimize_panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close_panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(minimize_panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(close_panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Full Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Identification no.:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password:");

        phonetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phonetxtKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phone:");

        gendertxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gendertxt.setForeground(new java.awt.Color(255, 255, 255));
        gendertxt.setText("Gender:");

        malebutton.setBackground(new java.awt.Color(0, 0, 51));
        malebutton.setForeground(new java.awt.Color(255, 255, 255));
        malebutton.setSelected(true);
        malebutton.setText("Male");
        malebutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        femalebutton.setBackground(new java.awt.Color(0, 0, 51));
        femalebutton.setForeground(new java.awt.Color(255, 255, 255));
        femalebutton.setText("Female");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Image:");

        imagebutton.setText("Select image");
        imagebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagebuttonActionPerformed(evt);
            }
        });

        labelimage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelimage.setForeground(new java.awt.Color(255, 255, 255));
        labelimage.setText("image path");
        labelimage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Confirm Password:");

        buttonLogin.setBackground(new java.awt.Color(232, 92, 0));
        buttonLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonLogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogin.setText("Register");
        buttonLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonLoginMouseExited(evt);
            }
        });
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });

        existedacc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        existedacc.setForeground(new java.awt.Color(255, 0, 0));
        existedacc.setText("Already have an Account? Login!");
        existedacc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                existedaccMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                existedaccMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                existedaccMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gendertxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imagebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ictxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(malebutton)
                        .addGap(18, 18, 18)
                        .addComponent(femalebutton))
                    .addComponent(Nametxt)
                    .addComponent(addresstxt)
                    .addComponent(phonetxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pwdtxt)
                    .addComponent(cfmpwdtxt)
                    .addComponent(labelimage, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(existedacc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nametxt)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addresstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ictxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(phonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel6)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pwdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cfmpwdtxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(malebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gendertxt)
                    .addComponent(femalebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imagebutton)
                    .addComponent(labelimage)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(existedacc)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Close_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_labelMouseClicked

        System.exit(0);  //Set Exit function. Exit when Clicked on it after 0s
    }//GEN-LAST:event_Close_labelMouseClicked

    private void buttonLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLoginMouseEntered
    buttonLogin.setBackground(new Color(255,146,73));

    }//GEN-LAST:event_buttonLoginMouseEntered

    private void buttonLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLoginMouseExited
     buttonLogin.setBackground(new Color(232,92,0));

    }//GEN-LAST:event_buttonLoginMouseExited

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed

    String gender = "Male";
    if(femalebutton.isSelected()){
        gender = "Female";
    }
    
     boolean filled = true;
     
     String fname = Nametxt.getText();
        String address = addresstxt.getText();
        String identification = ictxt.getText();
        String number = phonetxt.getText();
        String pwd = String.valueOf(pwdtxt.getPassword());
        String cfmpwd = String.valueOf(cfmpwdtxt.getPassword());
        
        if(fname.trim().equals("") || address.trim().equals("") || number.trim().equals("")
                || pwd.trim().equals("") || cfmpwd.trim().equals("")){
            JOptionPane.showMessageDialog(null, "All the Fields shouldn't be empty", "Empty Fields",2);
            filled = false;
        }else{
            if(!pwd.equals(cfmpwd)){
                JOptionPane.showMessageDialog(null, "Password Doesn't Match", "Confirm Password", 2);
                filled = false;
            }else{
                JOptionPane.showMessageDialog(null, "Account has been created");
                filled = true;
            }
        }  
    }//GEN-LAST:event_buttonLoginActionPerformed

    private void close_panel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_panel2MouseEntered

        //Effect color After clicked
        close_panel2.setBackground(new Color(255,0,0));
    }//GEN-LAST:event_close_panel2MouseEntered

    private void close_panel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_panel2MouseExited
        //Change effect when user clicked on the X button to exit
        //Original color Before click
        close_panel2.setBackground(new Color(0,0,51));
    }//GEN-LAST:event_close_panel2MouseExited

    private void minimize_panel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_panel2MouseEntered
        minimize_panel2.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_minimize_panel2MouseEntered

    private void minimize_panel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_panel2MouseExited
        minimize_panel2.setBackground(new Color(0,0,51));
    }//GEN-LAST:event_minimize_panel2MouseExited

    private void Close_label2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_label2MouseClicked
        System.exit(0);  //Set Exit function. Exit when Clicked on it after 0s
    }//GEN-LAST:event_Close_label2MouseClicked

    private void Close_label2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_label2MouseEntered
        close_panel2.setBackground(new Color(255,0,0));
    }//GEN-LAST:event_Close_label2MouseEntered

    private void Close_label2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_label2MouseExited
        close_panel2.setBackground(new Color(0,0,51));
    }//GEN-LAST:event_Close_label2MouseExited

    private void minimize_label2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_label2MouseClicked
        //Set to Minimize window function as it's a part of JFrame
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimize_label2MouseClicked

    private void minimize_label2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_label2MouseEntered
        minimize_panel2.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_minimize_label2MouseEntered

    private void minimize_label2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_label2MouseExited
        minimize_panel2.setBackground(new Color(0,0,51));
    }//GEN-LAST:event_minimize_label2MouseExited

    private void phonetxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonetxtKeyTyped
        //Allow only Numbers. If user tye Alphebet its wont able to show
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_phonetxtKeyTyped

    private void imagebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagebuttonActionPerformed
        //Select an image and set the image path into a (imagebutton & imagelabel)
        String path = null;
        
        JFileChooser chooser = new JFileChooser();
        
        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        
        //File Extension
        FileNameExtensionFilter extension = new FileNameExtensionFilter("Images",".jpg",".png",".jpeg");
        chooser.addChoosableFileFilter(extension);
        
        int filestate = chooser.showSaveDialog(null);
        
        //Check if the User Select an Image
        if(filestate == JFileChooser.APPROVE_OPTION){
            File selectedImage = chooser.getSelectedFile();
            path = selectedImage.getAbsolutePath();
            labelimage.setText(path);  //Display the image source/link
            
            image_path = path;
        }
    }//GEN-LAST:event_imagebuttonActionPerformed

    private void existedaccMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_existedaccMouseEntered
       // Color effect After Click
        existedacc.setForeground(new Color(255,51,51));
        
        Border label_border = BorderFactory.createMatteBorder(0,0,1,0, Color.red);
        existedacc.setBorder(label_border);
    }//GEN-LAST:event_existedaccMouseEntered

    private void existedaccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_existedaccMouseClicked
        MainLoginClass mainlogin = new MainLoginClass();
        mainlogin.setVisible(true);
    }//GEN-LAST:event_existedaccMouseClicked

    private void existedaccMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_existedaccMouseExited
        existedacc.setForeground(Color.red);
        existedacc.setBorder(null);
    }//GEN-LAST:event_existedaccMouseExited
    
    //Create a unction to verify the Empty fields
    public boolean verifyFields(){
        String fname = Nametxt.getText();
        String address = addresstxt.getText();
        String identification = ictxt.getText();
        String number = phonetxt.getText();
        String pwd = String.valueOf(pwdtxt.getPassword());
        String cfmpwd = String.valueOf(cfmpwdtxt.getPassword());
        
        if(fname.trim().equals("") || address.trim().equals("") || number.trim().equals("")
                || pwd.trim().equals("") || cfmpwd.trim().equals("")){
            JOptionPane.showMessageDialog(null, "All the Fields shouldn't be empty", "Empty Fields",2);
            return false;
        }
        
        //Check if the two password are equals
        else if(pwd.equals(cfmpwd)){
            JOptionPane.showMessageDialog(null, "Password Doesn't Match", "Confirm Password",2);
            return false;
        }else{
            return true;
        }      
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Close_label;
    private javax.swing.JLabel Close_label2;
    private javax.swing.JTextField Nametxt;
    private javax.swing.JTextField addresstxt;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JPasswordField cfmpwdtxt;
    private javax.swing.JPanel close_panel2;
    private javax.swing.JLabel existedacc;
    private javax.swing.JRadioButton femalebutton;
    private javax.swing.JLabel gendertxt;
    private javax.swing.JTextField ictxt;
    private javax.swing.JButton imagebutton;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel labelimage;
    private javax.swing.JRadioButton malebutton;
    private javax.swing.JLabel minimize_label2;
    private javax.swing.JPanel minimize_panel2;
    private javax.swing.JTextField phonetxt;
    private javax.swing.JPasswordField pwdtxt;
    // End of variables declaration//GEN-END:variables
}
